### ISSUE TITLE
Error with z3 formula

### ISSUE THREAD

**Issue by Zialus** [mht208/homebrew-formal#20]
```
Error: Failed to import: /usr/local/Homebrew/Library/Taps/mht208/homebrew-formal/z3.rb
z3: Unsupported special dependency :python
```

**Comment by Zialus** [comment]
You can actually remove it if you want, given that it is available on the main repo

https://github.com/Homebrew/homebrew-core/blob/master/Formula/z3.rb

**Comment by mht208** [comment]
Removed. Thank you.
