### ISSUE TITLE
verit

### ISSUE THREAD

**Issue by Junkil** [mht208/homebrew-formal#8]
There is an issue when installing verit

brew install verit
==> Installing verit from mht208/homebrew-formal
==> Downloading http://www.verit-solver.org/distrib/veriT-201107.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "verit"
Download failed: http://www.verit-solver.org/distrib/veriT-201107.tar.gz

**Comment by mht208** [comment]
I updated veriT to version 201410. Please check if the new version works for you.

**Comment by Junkil** [comment]
It works well. Thank you.
